name: "Scheduler"
on:
  schedule:
    - cron: '0/10 * * * *'
jobs:
  push_commit:
    name: PUSH
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit –-allow-empty -m "`date`"
          git push
