name: "scheduler"
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  push_commit:
    name: commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit --allow-empty -m "`date`"
          git push
